#!/bin/bash

export PACKAGE_CORE_NAME="podman"
export PACKAGE_CORE_BIN_NAME="$PACKAGE_CORE_NAME"
export PACKAGE_CORE_VERSION=v4.4.0
export PACKAGE_CORE_ORG="containers"

export PACKAGE_CORE_RELEASE_DOWNLOAD="https://github.com/${PACKAGE_CORE_ORG}/podman/releases/download"
