#!/bin/bash

install() {
  # prepare vars
  local name="$PACKAGE_CORE_NAME"

  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local os="$PACKAGE_OS"
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # case $arch in
  # arm64) ;;

  # amd64)
  #   arch="x86_64"
  #   ;;
  # *)
  #   log::error "[$(timestamp)] unsupport arch: $arch"
  #   return 1
  #   ;;
  # esac
  # #

  # template os
  # case $os in
  # macos)
  #   pm install -y podman1
  #   ;;
  # ubuntu)
  #   pm install -y podman2
  #   ;;
  # centos)
  #   pm install -y podman3
  #   ;;
  # alpine)
  #   pm install -y podman4
  #   ;;
  # archlinux)
  #   pm install -y podman5
  #   ;;
  # archlinux)
  #   pm install -y podman5
  #   ;;
  # fedora)
  #   pm install -y podman6
  #   ;;
  # *)
  #   log::error "[$(timestamp)] unsupport os: $os ($(uname -m))"
  #   return 1
  # esac

  #
  local download_name=""
  local tmp_file="$name.tar.gz"
  local source_bin_file=""
  case $platform in
  darwin)
    download_name="podman-remote-release-darwin_${arch}.zip"
    tmp_file="$download_name"
    source_bin_file="./podman-${PACKAGE_CORE_VERSION#v}/usr/bin/podman"
    ;;
  linux)
    download_name="podman-remote-static-linux_${arch}.tar.gz"
    tmp_file="$download_name"
    source_bin_file="./podman-remote-static-linux_${arch}"
    ;;
  *)
    log::error "[$(timestamp)] unsupport platform: $platform"
    return 1
    ;;
  esac

  # files

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/containers/podman/releases
  # example:
  #   https://github.com/containers/podman/releases/download/v4.4.0/podman-remote-release-darwin_amd64.zip
  #   https://github.com/containers/podman/releases/download/v4.4.0/podman-remote-release-darwin_arm64.zip
  #   https://github.com/containers/podman/releases/download/v4.4.0/podman-remote-static-linux_amd64.tar.gz
  #   https://github.com/containers/podman/releases/download/v4.4.0/podman-remote-static-linux_arm64.tar.gz
  # generate url
  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/$PACKAGE_CORE_VERSION/${download_name}"
  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][package][$name] downloading ..."
  os::download $tmp_file $url

  # extract
  log::info "[$(timestamp)][package][$name] extracting ..."
  os::extract $tmp_file

  # install
  log::info "[$(timestamp)][package][$name] installing ..."
  os::install $source_bin_file $usr_bin_dir $name

  # clean
  log::info "[$(timestamp)][package][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
